# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(verbose_name='date published')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Position', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('Tel', models.CharField(blank=True, max_length=100)),
                ('Photo', models.ImageField(blank=True, upload_to='cv_site/static/images')),
                ('LinkedIn', models.CharField(blank=True, max_length=255)),
                ('Date1', models.CharField(blank=True, max_length=100)),
                ('StudyPlace1', models.CharField(blank=True, max_length=200)),
                ('Degree1', models.CharField(blank=True, max_length=200)),
                ('Date2', models.CharField(blank=True, max_length=100)),
                ('StudyPlace2', models.CharField(blank=True, max_length=200)),
                ('Degree2', models.CharField(blank=True, max_length=200)),
                ('Date3', models.CharField(blank=True, max_length=100)),
                ('StudyPlace3', models.CharField(blank=True, max_length=200)),
                ('Degree3', models.CharField(blank=True, max_length=200)),
                ('Date4', models.CharField(blank=True, max_length=100)),
                ('StudyPlace4', models.CharField(blank=True, max_length=200)),
                ('Degree4', models.CharField(blank=True, max_length=200)),
                ('Skill1', models.CharField(blank=True, max_length=255)),
                ('Skill2', models.CharField(blank=True, max_length=255)),
                ('Skill3', models.CharField(blank=True, max_length=255)),
                ('Skill4', models.CharField(blank=True, max_length=255)),
                ('Skill5', models.CharField(blank=True, max_length=255)),
                ('Skill6', models.CharField(blank=True, max_length=255)),
                ('Skill7', models.CharField(blank=True, max_length=255)),
                ('Skill8', models.CharField(blank=True, max_length=255)),
                ('Skill9', models.CharField(blank=True, max_length=255)),
                ('Skill10', models.CharField(blank=True, max_length=255)),
                ('Skill11', models.CharField(blank=True, max_length=255)),
                ('Skill12', models.CharField(blank=True, max_length=255)),
                ('Skill13', models.CharField(blank=True, max_length=255)),
                ('Skill14', models.CharField(blank=True, max_length=255)),
                ('Skill15', models.CharField(blank=True, max_length=255)),
                ('Skill16', models.CharField(blank=True, max_length=255)),
                ('Skill17', models.CharField(blank=True, max_length=255)),
                ('Skill18', models.CharField(blank=True, max_length=255)),
                ('Skill19', models.CharField(blank=True, max_length=255)),
                ('Skill20', models.CharField(blank=True, max_length=255)),
                ('Skill21', models.CharField(blank=True, max_length=255)),
                ('Skill22', models.CharField(blank=True, max_length=255)),
                ('Skill23', models.CharField(blank=True, max_length=255)),
                ('Skill24', models.CharField(blank=True, max_length=255)),
                ('Skill25', models.CharField(blank=True, max_length=255)),
                ('Skill26', models.CharField(blank=True, max_length=255)),
                ('Skill27', models.CharField(blank=True, max_length=255)),
                ('Skill28', models.CharField(blank=True, max_length=255)),
                ('Skill29', models.CharField(blank=True, max_length=255)),
                ('Skill30', models.CharField(blank=True, max_length=255)),
                ('Lang1', models.CharField(blank=True, max_length=100)),
                ('Lang2', models.CharField(blank=True, max_length=100)),
                ('Lang3', models.CharField(blank=True, max_length=100)),
                ('Lang4', models.CharField(blank=True, max_length=100)),
                ('Lang5', models.CharField(blank=True, max_length=100)),
                ('Cert1', models.CharField(blank=True, max_length=200)),
                ('Cert2', models.CharField(blank=True, max_length=200)),
                ('Cert3', models.CharField(blank=True, max_length=200)),
                ('Cert4', models.CharField(blank=True, max_length=200)),
                ('Cert5', models.CharField(blank=True, max_length=200)),
                ('Cert6', models.CharField(blank=True, max_length=200)),
                ('Cert7', models.CharField(blank=True, max_length=200)),
                ('Cert8', models.CharField(blank=True, max_length=200)),
                ('Cert9', models.CharField(blank=True, max_length=200)),
                ('Cert10', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
