# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
    ]
