# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20170208_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Lang1',
            field=models.CharField(blank=True, choices=[('Fluent', 'Fluent'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=100),
        ),
    ]
