# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20170208_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_1',
            new_name='Certificate_1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_10',
            new_name='Certificate_10',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_2',
            new_name='Certificate_2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_3',
            new_name='Certificate_3',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_4',
            new_name='Certificate_4',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_5',
            new_name='Certificate_5',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_6',
            new_name='Certificate_6',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_7',
            new_name='Certificate_7',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_8',
            new_name='Certificate_8',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Cert_9',
            new_name='Certificate_9',
        ),
    ]
