# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='UserName',
            new_name='Username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
