# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20170228_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Language_1_Quality',
            field=models.CharField(blank=True, choices=[('Fluent', 'Fluent'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=255, null=True),
        ),
    ]
