# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_20170228_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='cv_site/static/images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Username',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
