# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_auto_20170301_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.FileField(blank=True, upload_to='cv/static/images/'),
        ),
    ]
