# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0025_auto_20170302_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.FileField(blank=True, upload_to='/static/images/profile_photos/'),
        ),
    ]
