# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0028_auto_20170302_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PhotoName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Photo',
            field=models.FileField(blank=True, upload_to='cv/static/images/profile_photos/'),
        ),
    ]
